[profile.default]
names = true
sizes = true
ffi = true
fs_permissions = [{ access = "read", path = "./config/"}]


[fuzz]
runs = 32


[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
