/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as depositZapBtcVy from "./DepositZapBTC.vy";
export * as depositZapMorphoAaveV2UsdVy from "./DepositZapMorphoAaveV2USD.vy";
export * as depositZapUsdVy from "./DepositZapUSD.vy";
