/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as depositZapBtcVy from "./DepositZapBTC.vy";
import type * as depositZapMorphoAaveV2UsdVy from "./DepositZapMorphoAaveV2USD.vy";
import type * as depositZapUsdVy from "./DepositZapUSD.vy";

export type { depositZapBtcVy };

export type { depositZapMorphoAaveV2UsdVy };

export type { depositZapUsdVy };
