/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as aaveLendingPoolMockSol from "./AaveLendingPoolMock.sol";
import type * as addressProviderVy from "./AddressProvider.vy";
import type * as curvePoolVy from "./CurvePool.vy";
import type * as curveTokenV3Vy from "./CurveTokenV3.vy";
import type * as erc20MockVy from "./ERC20Mock.vy";
import type * as mockBoostDelegationProxyVy from "./MockBoostDelegationProxy.vy";
import type * as registryVy from "./Registry.vy";
import type * as aErc20Sol from "./aERC20.sol";

export type { aaveLendingPoolMockSol };

export type { addressProviderVy };

export type { curvePoolVy };

export type { curveTokenV3Vy };

export type { erc20MockVy };

export type { mockBoostDelegationProxyVy };

export type { registryVy };

export type { aErc20Sol };
